### ISSUE TITLE
Unexpected Confluent plugin repository

### ISSUE THREAD

**Issue by reugn** [trinodb/trino-maven-plugin#16]
I get this error
```
Error:  Failed to execute goal io.trino:trino-maven-plugin:11:check-spi-dependencies (default-check-spi-dependencies) on project: Failed to resolve dependencies. Failed to read artifact descriptor for io.trino:trino-spi:jar:361: Could not find artifact io.airlift:airbase:pom:110 in confluent (https://packages.confluent.io/maven/) -> [Help 1]
```
in a custom Trino connector project when building with GitHub actions workflow. It works fine on my local machine (gets the dependency from Maven Central), as well as on a Docker environment.

**Comment by cccs-tom** [comment]
+1

I am also encountering this. Seems to happen every time on Maven 3.8.2, but with Maven 3.6.3, the build passes just fine.

**Comment by wendigo** [comment]
Is this still an issue?
