### ISSUE TITLE
Support parallel builds

### ISSUE THREAD

**Issue by nielsbasjes** [trinodb/trino-maven-plugin#18]
My project ( https://github.com/nielsbasjes/yauaa ) has a Trino UDF which uses this plugin during the build.

When I build with `mvn -T 1C` (see https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3 )

I get this:
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in Yauaa : UDF : Trino (a.k.a. Presto SQL):
[WARNING] io.trino:trino-maven-plugin:11
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

**Comment by findepi** [comment]
We use parallel builds in Trino as well.

Would you be interested in sending a PR?

**Comment by nielsbasjes** [comment]
I know nothing of the internals of your plugin. If your plugin is already threadsafe then it is just a matter of adding the annotation.
If your plugin is not threadsafe (or it is jot known) it is a completely different thing.
Assessing if it is threadsafe usually means either digging through the entire code base or putting the entire thing in a synchronized block.

Do you know what the current status is?

**Comment by findepi** [comment]
I am not familiar with the plugin internals either.
@electrum would know better

**Comment by wendigo** [comment]
It was fixed in https://github.com/trinodb/trino-maven-plugin/commit/ebd33267326ab5ca6e28174c668fdc7dad83a61e
